main: com.gmail.markushygedombrowski.HLvagt
name: HLvagt
version: "1.0"
softdepend:  [Vault,WorldGuard,WorldEdit,HeadDatabase,Combat,HLUtils,Citizens,VagtProfiler]
commands:
  vagtspawn:
    aliases: ["setvagtspawn", "resetvagtspawn"]
    description: "vagtspawn system"
  vagt:
    description: "vagt"
  hlvagtreload:
    description: "reloads config"
  ansat:
    description: "ansæt vagter"
  vc:
    description: "vagt chat"
  gui:
    description: "mikkels gui"
  drop:
    description: "må droppe"
  fyr:
    description: "fyr vagter"
  aktivbuff:
    description: "vagt buff aktiv"
  guitest:
    description: "test gui"
  vresetall:
    aliases: ["vconfirmresetall", "vreset", "vexp", "vlevel",]
    description: "resetter alle vagter"